repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: \.json$
      - id: end-of-file-fixer
        exclude: \.json$
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types: [javascript]
        exclude: \.json$
